Build fix: AAPT2 error; unescaped apostrophe
When updating to SDK version 28, an error like this would appear
in the build log:
~~~~~~
:app:checkDebugManifest
:app:generateDebugBuildConfig
:app:prepareLintJar UP-TO-DATE
:app:generateDebugResValues
:app:generateDebugResources
:app:processDebugGoogleServices
Parsing json file: C:\Users\z\StudioProjects\carstream-android-auto\app\google-services.json
AGPBI: {"kind":"error","text":"error: unescaped apostrophe in string","sources":[{"file":"C:\\Users\\z\\StudioProjects\\carstream-android-auto\\app\\src\\main\\res\\values-it\\strings.xml","position":{"startLine":27,"startColumn":4,"startOffset":1761,"endColumn":72,"endOffset":1829}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: not a valid string.","sources":[{"file":"C:\\Users\\z\\StudioProjects\\carstream-android-auto\\app\\src\\main\\res\\values-it\\strings.xml","position":{"startLine":27,"startColumn":4,"startOffset":1761,"endColumn":72,"endOffset":1829}}],"original":"","tool":"AAPT"}
C:\Users\z\StudioProjects\carstream-android-auto\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-it\values-it.xml:89: error: unescaped apostrophe in string
C:\Users\z\StudioProjects\carstream-android-auto\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-it\values-it.xml:89: error: not a valid string.

:app:mergeDebugResources
Error: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
:app:mergeDebugResources FAILED

FAILURE: Build failed with an exception.
~~~~~~

This commit resolves the issue by adding the necessary escaping
backslash before the apostrophes in the offending strings.