Build fix: receive_from_phone string not found
When updating to SDK version 28, an error like this would appear
in the build log:
~~~~~~
:app:generateDebugResources
:app:processDebugGoogleServices
Parsing json file: C:\Users\z\StudioProjects\carstream-android-auto\app\google-services.json
:app:mergeDebugResources
:app:createDebugCompatibleScreenManifests
:app:processDebugManifest
:app:splitsDiscoveryTaskDebug
AGPBI: {"kind":"error","text":"error: resource string/receive_from_phone (aka com.google.android.kk:string/receive_from_phone) not found.","sources":[{"file":"C:\\Users\\z\\StudioProjects\\carstream-android-auto\\app\\src\\main\\res\\layout\\fragment_webview_car.xml","position":{"startLine":138}}],"original":"","tool":"AAPT"}
C:\Users\z\StudioProjects\carstream-android-auto\app\src\main\res\layout\fragment_webview_car.xml:139: error: resource string/receive_from_phone (aka com.google.android.kk:string/receive_from_phone) not found.
error: failed linking file resources.
~~~~~~

This commit resolves the issue by adding a receive_from_phone entry
in the values/strings.xml file with the value "Receive from phone".
I am not sure if this is what that value would have originally expanded
to. The string is referred to by fragment_webview_car (as shown in the
error), but the (English) definition for the string appears nowhere in
the project. Perhaps this is from an older version of some API and is
no longer available due to the update. At the time of this writing,
there is a definition in values-ro/strings.xml which expands to
"Primire" (and I don't know what that means). I tried to search for
clues on the internets about where this might be defined and how to
cope with the loss, but this might have been too obscure or specific
to get any good leads. String identifiers are usually pretty true
to their English expansion, so "Receive from phone" it is.