Build fix: okhttp3 contains Java 8 bytecode.
When updating to SDK version 28, an error like this would appear
in the build log:
~~~~~~
:app:compileDebugSources
:app:mergeDebugShaders
:app:compileDebugShaders
:app:generateDebugAssets
:app:mergeDebugAssets
:app:transformClassesWithRealmTransformerForDebug
com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\z\.gradle\caches\modules-2\files-2.1\com.squareup.okhttp3\okhttp\4.0.0-alpha01\5d58cd3772c4a977ab105b07d5698091ee5e6834\okhttp-4.0.0-alpha01.jar
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[...]
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\z\.gradle\caches\modules-2\files-2.1\com.squareup.okhttp3\okhttp\4.0.0-alpha01\5d58cd3772c4a977ab105b07d5698091ee5e6834\okhttp-4.0.0-alpha01.jar
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:550)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.lambda$convertToDexArchive$1(DexArchiveBuilderTransform.java:488)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
[...]
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing okhttp3/internal/ws/RealWebSocket.class
The dependency contains Java 8 bytecode. Please enable desugaring by adding the following to build.gradle
android {
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
}
See https://developer.android.com/studio/write/java8-support.html for details. Alternatively, increase the minSdkVersion to 26 or above.

	at com.android.builder.dexing.DxDexArchiveBuilder.getExceptionToRethrow(DxDexArchiveBuilder.java:143)
	at com.android.builder.dexing.DxDexArchiveBuilder.convert(DxDexArchiveBuilder.java:89)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:545)
	... 6 more
Caused by: com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
	at com.android.dx.cf.code.Simulator$SimVisitor.visitConstant(Simulator.java:711)
	at com.android.dx.cf.code.BytecodeArray.parseInstruction(BytecodeArray.java:781)
	at com.android.dx.cf.code.Simulator.simulate(Simulator.java:103)
[...]

:app:transformClassesWithDexBuilderForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\z\.gradle\caches\modules-2\files-2.1\com.squareup.okhttp3\okhttp\4.0.0-alpha01\5d58cd3772c4a977ab105b07d5698091ee5e6834\okhttp-4.0.0-alpha01.jar
[...]
~~~~~~

This commit is a workaround that sets compileOptions.sourceCompatibility
and compileOptions.targetCompatibility as suggested by the build system's
error message.