Build fix: AAPT2 error; <item> inner element must either...
When updating to SDK version 28, an error like this would appear
in the build log:
~~~~~~
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Error: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
~~~~~~

Further into the log, there will be errors like this:
==========
:app:checkDebugManifest
:app:generateDebugBuildConfig
:app:prepareLintJar
:app:generateDebugResValues
:app:generateDebugResources
:app:processDebugGoogleServices
Parsing json file: C:\Users\z\StudioProjects\carstream-android-auto\app\google-services.json
AGPBI: {"kind":"error","text":"error: \u003citem\u003e inner element must either be a resource reference or empty.","sources":[{"file":"C:\\Users\\z\\.gradle\\caches\\transforms-1\\files-1.1\\aauto-sdk-v4.5.aar\\f96625b74a7b23c8dec4d8b375491929\\res\\values\\ids.xml","position":{"startLine":19,"startColumn":2,"startOffset":347,"endLine":21,"endColumn":9,"endOffset":400}}],"original":"","tool":"AAPT"}
[...]
C:\Users\z\StudioProjects\carstream-android-auto\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:2878: error: <item> inner element must either be a resource reference or empty.
[...]

:app:mergeDebugResources
Error: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
:app:mergeDebugResources FAILED
==========

This commit overrides the errant <item> elements to provide a
definition that the newer build system is happy with.

This solution is based off of the following Stack Overflow answer:
https://stackoverflow.com/a/53332571