Prep work for updates of SDK (v26->v28) and other dependencies (#229)
* Build fix: AAPT2 error; <item> inner element must either...

When updating to SDK version 28, an error like this would appear
in the build log:
~~~~~~
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Error: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
~~~~~~

Further into the log, there will be errors like this:
==========
:app:checkDebugManifest
:app:generateDebugBuildConfig
:app:prepareLintJar
:app:generateDebugResValues
:app:generateDebugResources
:app:processDebugGoogleServices
Parsing json file: C:\Users\z\StudioProjects\carstream-android-auto\app\google-services.json
AGPBI: {"kind":"error","text":"error: \u003citem\u003e inner element must either be a resource reference or empty.","sources":[{"file":"C:\\Users\\z\\.gradle\\caches\\transforms-1\\files-1.1\\aauto-sdk-v4.5.aar\\f96625b74a7b23c8dec4d8b375491929\\res\\values\\ids.xml","position":{"startLine":19,"startColumn":2,"startOffset":347,"endLine":21,"endColumn":9,"endOffset":400}}],"original":"","tool":"AAPT"}
[...]
C:\Users\z\StudioProjects\carstream-android-auto\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:2878: error: <item> inner element must either be a resource reference or empty.
[...]

:app:mergeDebugResources
Error: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
:app:mergeDebugResources FAILED
==========

This commit overrides the errant <item> elements to provide a
definition that the newer build system is happy with.

This solution is based off of the following Stack Overflow answer:
https://stackoverflow.com/a/53332571

* Build fix: AAPT2 error; unescaped apostrophe

When updating to SDK version 28, an error like this would appear
in the build log:
~~~~~~
:app:checkDebugManifest
:app:generateDebugBuildConfig
:app:prepareLintJar UP-TO-DATE
:app:generateDebugResValues
:app:generateDebugResources
:app:processDebugGoogleServices
Parsing json file: C:\Users\z\StudioProjects\carstream-android-auto\app\google-services.json
AGPBI: {"kind":"error","text":"error: unescaped apostrophe in string","sources":[{"file":"C:\\Users\\z\\StudioProjects\\carstream-android-auto\\app\\src\\main\\res\\values-it\\strings.xml","position":{"startLine":27,"startColumn":4,"startOffset":1761,"endColumn":72,"endOffset":1829}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: not a valid string.","sources":[{"file":"C:\\Users\\z\\StudioProjects\\carstream-android-auto\\app\\src\\main\\res\\values-it\\strings.xml","position":{"startLine":27,"startColumn":4,"startOffset":1761,"endColumn":72,"endOffset":1829}}],"original":"","tool":"AAPT"}
C:\Users\z\StudioProjects\carstream-android-auto\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-it\values-it.xml:89: error: unescaped apostrophe in string
C:\Users\z\StudioProjects\carstream-android-auto\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-it\values-it.xml:89: error: not a valid string.

:app:mergeDebugResources
Error: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
:app:mergeDebugResources FAILED

FAILURE: Build failed with an exception.
~~~~~~

This commit resolves the issue by adding the necessary escaping
backslash before the apostrophes in the offending strings.

* Build fix: receive_from_phone string not found

When updating to SDK version 28, an error like this would appear
in the build log:
~~~~~~
:app:generateDebugResources
:app:processDebugGoogleServices
Parsing json file: C:\Users\z\StudioProjects\carstream-android-auto\app\google-services.json
:app:mergeDebugResources
:app:createDebugCompatibleScreenManifests
:app:processDebugManifest
:app:splitsDiscoveryTaskDebug
AGPBI: {"kind":"error","text":"error: resource string/receive_from_phone (aka com.google.android.kk:string/receive_from_phone) not found.","sources":[{"file":"C:\\Users\\z\\StudioProjects\\carstream-android-auto\\app\\src\\main\\res\\layout\\fragment_webview_car.xml","position":{"startLine":138}}],"original":"","tool":"AAPT"}
C:\Users\z\StudioProjects\carstream-android-auto\app\src\main\res\layout\fragment_webview_car.xml:139: error: resource string/receive_from_phone (aka com.google.android.kk:string/receive_from_phone) not found.
error: failed linking file resources.
~~~~~~

This commit resolves the issue by adding a receive_from_phone entry
in the values/strings.xml file with the value "Receive from phone".
I am not sure if this is what that value would have originally expanded
to. The string is referred to by fragment_webview_car (as shown in the
error), but the (English) definition for the string appears nowhere in
the project. Perhaps this is from an older version of some API and is
no longer available due to the update. At the time of this writing,
there is a definition in values-ro/strings.xml which expands to
"Primire" (and I don't know what that means). I tried to search for
clues on the internets about where this might be defined and how to
cope with the loss, but this might have been too obscure or specific
to get any good leads. String identifiers are usually pretty true
to their English expansion, so "Receive from phone" it is.

* Build fix: "send_to_car" not in default locale

When updating to SDK version 28, an error like this would appear
in the build log:
~~~~~~
C:\Users\z\StudioProjects\carstream-android-auto\app\src\main\res\values-ro\strings.xml:14: Error: "send_to_car" is translated here but not found in default locale [ExtraTranslation]
    <string name="send_to_car">Trimitere la masina</string>
            ~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "ExtraTranslation":
   If a string appears in a specific language translation file, but there is
   no corresponding string in the default locale, then this string is probably
   unused. (It's technically possible that your application is only intended
   to run in a specific locale, but it's still a good idea to provide a
   fallback.).

   Note that these strings can lead to crashes if the string is looked up on
   any locale not providing a translation, so it's important to clean them
   up.
~~~~~~

This commit resolves the issue by adding a send_to_car entry
in the values/strings.xml file with the value "Send to car".
This might be similar in nature to the "receive_from_phone",
just different in that the string isn't explicitly referenced
in the project. I don't like the idea of potential crashes,
so I'm putting a defualt value in English and hoping that its
identifier is representative of what it's supposed to expand
to.

* Build/crash fix: Didn't find class "okio.Buffer"

okio is a dependency of okhttp3. Presumably, it wasn't necessary
for this dependency to be specified in the earlier Android SDK
version (not needed on 26, maybe needed on 28), or perhaps this
was pulled by a newer version of okhttp3 (not needed for
okhttp3-3.9.1, maybed needed for okhttp3-4.0.0-alpha01). At any
rate, this commit prepares the codebase for such version bumps.

I believe I encountered this as a runtime crash, though this
problem, by its nature, could be encountered at build time
depending on configuration:
https://talk.remobjects.com/t/build-error-when-including-com-squareup-okio-jar/18249

The error message encountered was something like this:

  java.lang.ClassNotFoundException: Didn't find class "okio.Buffer"

(It was longer, but I can't be more specific because I no longer
have the log for it.)

* Build fix: okhttp3 contains Java 8 bytecode.

When updating to SDK version 28, an error like this would appear
in the build log:
~~~~~~
:app:compileDebugSources
:app:mergeDebugShaders
:app:compileDebugShaders
:app:generateDebugAssets
:app:mergeDebugAssets
:app:transformClassesWithRealmTransformerForDebug
com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\z\.gradle\caches\modules-2\files-2.1\com.squareup.okhttp3\okhttp\4.0.0-alpha01\5d58cd3772c4a977ab105b07d5698091ee5e6834\okhttp-4.0.0-alpha01.jar
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[...]
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\z\.gradle\caches\modules-2\files-2.1\com.squareup.okhttp3\okhttp\4.0.0-alpha01\5d58cd3772c4a977ab105b07d5698091ee5e6834\okhttp-4.0.0-alpha01.jar
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:550)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.lambda$convertToDexArchive$1(DexArchiveBuilderTransform.java:488)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
[...]
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing okhttp3/internal/ws/RealWebSocket.class
The dependency contains Java 8 bytecode. Please enable desugaring by adding the following to build.gradle
android {
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
}
See https://developer.android.com/studio/write/java8-support.html for details. Alternatively, increase the minSdkVersion to 26 or above.

	at com.android.builder.dexing.DxDexArchiveBuilder.getExceptionToRethrow(DxDexArchiveBuilder.java:143)
	at com.android.builder.dexing.DxDexArchiveBuilder.convert(DxDexArchiveBuilder.java:89)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:545)
	... 6 more
Caused by: com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
	at com.android.dx.cf.code.Simulator$SimVisitor.visitConstant(Simulator.java:711)
	at com.android.dx.cf.code.BytecodeArray.parseInstruction(BytecodeArray.java:781)
	at com.android.dx.cf.code.Simulator.simulate(Simulator.java:103)
[...]

:app:transformClassesWithDexBuilderForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\z\.gradle\caches\modules-2\files-2.1\com.squareup.okhttp3\okhttp\4.0.0-alpha01\5d58cd3772c4a977ab105b07d5698091ee5e6834\okhttp-4.0.0-alpha01.jar
[...]
~~~~~~

This commit is a workaround that sets compileOptions.sourceCompatibility
and compileOptions.targetCompatibility as suggested by the build system's
error message.